# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 412dc4f0af90bd1b703f5b5e06c606c8f218428dc72e1cede5e0496d3214be0501871ead39499d25cf52eaa89bda01c8b36ea26e37337c1b33c613e60fb159c6

test:
  secret_key_base: bdad5a352b291b66dc6768c55f1dbcc61f370ec29e4d5488afb941628c6b8cdcfdff37923814b8edadb0345765edc8c37ae412d19b3aeb3156d270769cff51b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
